version: 2
updates:
  # Maintain GitHub Action runners
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: dev
    commit-message:
      prefix: "[Dependabot]"
    labels:
      - Dependencies
    assignees:
      - Paebbels
      - Umarcor
    reviewers:
      - Paebbels
      - Umarcor
    schedule:
      interval: "daily"    # Checks on Monday trough Friday.
